apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-operator-bootstrap
  namespace: argocd-operator-system
  argocd.argoproj.io/sync-options: Prune=confirm
spec:
  project: default
  source:
    repoURL: 'https://github.com/dtolgyg/argocd-operator-install.git'
    targetRevision: HEAD
    path: argocd-operator-config
    kustomize: {}
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: argocd-operator-system 
  syncPolicy:
    syncOptions:
      - ServerSideApply=true
    automated:
      enabled: false
